### ISSUE TITLE
XCODE tag are not parsed on display

### ISSUE THREAD

**Issue by BigKev73** [XoopsModules25x/about#19]
If you use the DTHML editor and use the XCODE from the editor. Those xcodes are displayed when the page is viewed.

**Comment by mambax7** [comment]
Do you have this change to the Core?
https://github.com/XOOPS/XoopsCore25/pull/924

**Comment by mambax7** [comment]
OK, I see it. It might be that it was just stored in the DB this way. 
 I'll take a look at that.

**Comment by mambax7** [comment]
check my repository and see if it works for you now:
https://github.com/mambax7/about

Because it is normally only for the Admin to use it, the TinyMCE was the default

**Comment by BigKev73** [comment]
Yes, that appears to have resolved it. Thanks!
