### ISSUE TITLE
Uncaught type error treeview is not a function

### ISSUE THREAD

**Issue by Supergran** [XoopsModules25x/about#5]
came across this error in the about module. The error relates to this piece of script found in about\templates\about_page.tpl
`<script type="text/javascript">
$(function() {
    $("#tree").treeview({
        animated: "medium",
        persist: "location",
        collapsed: true,
        unique: true
    });
})
</script>`

I've checked Mamba's fork for the latest changes but the same error presents.  Interestingly I downloaded what I thought was the latest release from the[ link given on the Xoops site's News tab](http://xoops.org/modules/news/article.php?storyid=6773) where Mamba mentioned the modules but both the latest release and the RC2 version have the same date and the changelog.txt files in both say RC2.  Mamba's fork files show Final Release in the changelog.txt so it may be that the Final Version commits didn't make it. 
Not sure how much of an issue the treeview thing is but checking the Final release thing is probably worthwhile given Mamba's obvious hard work on this.  Great, simple content module for Xoops.  Really useful.  Thank you.
Jan

**Comment by mambax7** [comment]
Thank you for letting me know about the release confusion. I fixed the release issue, i.e. the Final release does contains now the 1.04 Final files.
Now I'll have to look into the error that you've reported. 
I'll keep you posted...
